on:
  push:
    branches:
      - master

name: Deploy String boot to Amazon EC2

env:
  PROJECT_NAME: my-app-backend

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set yml variable
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/main/resources/application-proddb.yml'
        env:
          spring.datasource.url: ${{ secrets.MYSQL_URL }} 
          spring.datasource.username: ${{ secrets.MYSQL_USERNAME }} 
          spring.datasource.password: ${{ secrets.MYSQL_PASSWORD }} 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://leelee-my-app-bucket/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name my-app --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name EC2-Deploy --s3-location bucket=leelee-my-app-bucket,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
